<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SarthakDell" failures="1" tests="3" name="com.TestNG.Day10_Jan_17_2024_Introduction_to_TestNG.DependsOnMethods" time="0.013" errors="0" timestamp="2024-01-17T22:37:44 EST" skipped="1">
  <testcase classname="com.TestNG.Day10_Jan_17_2024_Introduction_to_TestNG.DependsOnMethods" name="testCase1" time="0.009"/>
  <testcase classname="com.TestNG.Day10_Jan_17_2024_Introduction_to_TestNG.DependsOnMethods" name="testCase2" time="0.004">
    <failure message="I am deliberately failing test case no 2" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: I am deliberately failing test case no 2
at org.testng.Assert.fail(Assert.java:111)
at com.TestNG.Day10_Jan_17_2024_Introduction_to_TestNG.DependsOnMethods.testCase2(DependsOnMethods.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.TestNG.Day10_Jan_17_2024_Introduction_to_TestNG.DependsOnMethods" name="testCase3" time="0.000">
    <skipped/>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- com.TestNG.Day10_Jan_17_2024_Introduction_to_TestNG.DependsOnMethods -->
